ktor:
  application:
    modules:
      - com.flipedds.ApplicationKt.module
  deployment:
    port: 8080
    host: "0.0.0.0"
storage:
  driverClassName: $DRIVER
  jdbcURL: $DB_URL
  user: $DB_USER
  password: $DB_PASSWORD

jwt:
  secret: "secret"
  realm: "ktor aperreio zero"
  issuer: "https://jwt-provider-domain/"
  audience: "jwt-audience"